### ISSUE TITLE
[Request] Refactor to return computed width + separate function to update width on HTML element

### ISSUE THREAD

**Issue by domantasjurkus** [wojtekmaj/update-input-width#15]
Hello, first of all thanks for the library - we're using it in a React project, however we are facing issues with rendering due to the following line:
https://github.com/wojtekmaj/update-input-width/blob/ded62733db62e66bd5bdbf70a5fddbf8e608f494/src/index.js#L67

Updating the element like this makes the library not very React-friendly - DOM modifications should not be done on the element itself, but rather be relayed to the render method of each component.

A good addition to your lib would be splitting the logic inside `updateInputWidth` into a separate `getUpdatedInputWidth` and then allowing the consumer to set the width however they please (pass as props in the case of React).

Happy to do a PR if you think the request is reasonable.

**Comment by domantasjurkus** [comment]
Realised I can just `measureText` and set the width myself - over-engineering as always...

**Comment by wojtekmaj** [comment]
Hmmm, that package wasn't created with any specific UI library in mind, but I do hear you here. Best I could propose though to make it React-friendly would be to create a reusable hook using, for example, useImperativeHandle (a rare one, I know!).
