### ISSUE TITLE
getFontShorthand returns "    / " when element is not mounted in DOM tree

### ISSUE THREAD

**Issue by timkingman** [wojtekmaj/update-input-width#5]
With 7.8.1, rendering a `DatePicker` in a `react-responsive-modal` fails. Rendering inside the same modal after a delay works.

The error happens in line 20 of `Input.jsx` https://github.com/wojtekmaj/react-date-picker/commit/e0cc5760c4e263e5a258be0f7f88f76e0af2c6a2 , and this might technically be a bug in `getFontShorthand()` from `update-input-width`.

It looks like this is because the modal's content is initially created outside of the document's DOM and `document.getComputedStyle(element)` doesn't contain any font styles.

If the modal appears first and then displays the form after a delay (e.g. ajax loading), rendering works.

https://codesandbox.io/s/brave-fermat-u3t45

**Comment by wojtekmaj** [comment]
After more careful analysis some fix will still be necessary on React-Date-Picker's side, so you will see the fix in the next release.
